//
// Created by Ian Parker on 18/04/2026.
//

#include <cstdio>
#include <algorithm>

#include <yaml-cpp/yaml.h>

using namespace std;

void parseDataDefinition(const string& parentName, const string& parentId, YAML::Node node, map<string, string>& definitions)
{
    for (YAML::const_iterator it = node.begin(); it!=node.end(); ++it)
    {
        auto nodeName = it->first.as<string>();
        string id;
        if (!parentId.empty())
        {
            id = parentId + "/";
        }

        id += nodeName;
        string name = parentName + "_" + nodeName;

        auto child = it->second;

        if (child.Type() == YAML::NodeType::Map)
        {
            if (child["dataRef"] || child["lua"])
            {
                definitions.try_emplace(name, id);
            }
            else
            {
                parseDataDefinition(name, id, child, definitions);
            }
        }
        else
        {
            definitions.try_emplace(name, id);
        }
    }
}

void addDefinitions(FILE* headerFile, YAML::Node yaml, string parentName)
{
    map<string, string> definitions;
    parseDataDefinition("DATA", "", yaml, definitions);
    for (auto& it : definitions)
    {
        string name = it.first;
        string& id = it.second;
        transform(name.begin(), name.end(), name.begin(), ::toupper);
        std::replace( name.begin(), name.end(), '/', '_');
        fprintf(headerFile, "#define %s \"%s\"\n", name.c_str(), id.c_str());
    }
}

int main(int argc, char** argv)
{
    if (argc < 3)
    {
        printf("Usage: %s <dataPath> <headerPath>\n", argv[0]);
        return 1;
    }

    const char* dataPath = argv[1];
    const char* headerPath = argv[2];
    printf("%s: dataPath=%s\n", argv[0], dataPath);
    printf("%s: headerPath=%s\n", argv[0], headerPath);

    auto yaml = YAML::LoadFile(dataPath);

    FILE* headerFile = fopen(headerPath, "w");
    if (headerFile == nullptr)
    {
        printf("Failed to open header file %s\n", headerPath);
        return 1;
    }

    fprintf(headerFile, "// This file is generated by %s\n", argv[0]);
    fprintf(headerFile, "// DO NOT EDIT\n\n");
    fprintf(headerFile, "#pragma once\n\n");
    addDefinitions(headerFile, yaml["data"], "DATA");
    addDefinitions(headerFile, yaml["commands"], "COMMANDS");

    fclose(headerFile);

    return 0;
}

